
#ifndef __pxservices__
#define __pxservices__

typedef enum
{







 PXSvSetMessageFun ,
 PXSvMbxInstallHnd ,
 PXSvMcTakeBlk ,
 PXSvMcReturnBlk ,
 PXSvMcInsertBlk ,
 PXSvMsgReceive ,
 PXSvMsgReceive_Waiting ,
 PXSvMsgReceive_EvWait ,
 PXSvMsgReceive_EvWait_Waiting ,
 PXSvMsgReceive_NoWait ,
 PXSvMsgSend ,
 PXSvMsgSend_Prio ,
 PXSvMsgRequest ,
 PXSvMsgRequest_EvWait ,
 PXSvMsgRequest_NoWait ,
 PXSvMsgEnvelop ,
 PXSvMsgEnvelop_EvWait ,
 PXSvMsgEnvelop_NoWait ,
 PXSvMsgRelease ,
 PXSvMsgSetSize ,
 PXSvMsgInstallRelmbx ,
 PXSvMsgAwaitRel ,
 PXSvMsgAwaitRel_Waiting ,
 PXSvMsgAwaitRel_EvWait ,
 PXSvMsgAwaitRel_EvWait_Waiting ,
 PXSvMsgAwaitRel_NoWait ,
 PXSvMsgSetToAwaitRel ,
 PXSvMsgReleaseAllMsg ,
 PXSvTaskGetModebits ,
 PXSvSetModebits ,
 PXSvClearModebits ,
 PXSvSetError ,
 PXSvSetAppinfo ,
 PXSvSetTimeslices ,
 PXSvDie ,
 PXSvAwaitEvents ,
 PXSvAwaitEvents_Waiting ,
 PXSvResetEvents ,
 PXSvTaskCreate ,
 PXSvTaskSuspend ,
 PXSvTaskResume ,
 PXSvTaskSetPrio ,
 PXSvSetTraceFunc ,
 PXSvGetCoreId ,
 PXSvGetGlobalServerMbx ,
 PXSvMcRemoveBlk ,
 PXSvObjSetName ,
 PXSvPxmReadRegNo ,
 PXSvPxmWriteRegNo ,
 PXSvAbortSetup ,
 PXSvAbortSetjmp ,
 PXSvAbortCleanup ,
 PXSvDelaySched ,
 PXSvTaskSignalEvents ,
 PXSvGetPrivileges ,
 PXSvSetPrivileges ,
 PXSvIntEnable ,
 PXSvIntDisable ,
 PXSvMcGetSize ,
 PXSvMcGetType ,
 PXSvMcResolveDefault ,
 PXSvMsgGetData ,
 PXSvMsgRelDataAccess ,
 PXSvMsgGetSize ,
 PXSvMsgGetBuffersize ,
 PXSvMsgGetOwner ,
 PXSvOpoolGetCurrentCapacity ,
 PXSvOpoolGetType ,
 PXSvOpoolResolveDefault ,
 PXSvGetSavedEvents ,
 PXSvGetAbortingEvents ,
 PXSvGetId ,
 PXSvGetError ,
 PXSvGetAppinfo ,
 PXSvGetTimeslices ,
 PXSvTaskGetPrio ,
 PXSvTaskGetMbx ,
 PXSvTickGetCount ,
 PXSvTickSetTicksPerSecond ,
 PXSvTickGetTimeInMilliSeconds ,
 PXSvTickGetTicksFromMilliSeconds ,
 PXSvVersion ,
 PXSvGetObjsize ,
 PXSvGetAbortFrameSize ,
 PXSvTaskGetSize ,
 PXSvMcGetVarsizedOverhead ,
 PXSvObjGetName ,
 PXSvToRequest ,
 PXSvToStart ,
 PXSvToStop ,
 PXSvToRelease ,
 PXSvToChange ,
 PXSvPeRequest ,
 PXSvPeStart ,
 PXSvPeStop ,
 PXSvPeRelease ,
 PXSvPeChange ,
 PXSvDelayRequest ,
 PXSvDelayRequest_EvWait ,
 PXSvDelayRequest_NoWait ,
 PXSvDelayRelease ,
 PXSvInterruptRequest ,
 PXSvInterruptRequest_EvWait ,
 PXSvInterruptRequest_NoWait ,
 PXSvInterruptRelease ,
 PXSvMbxRequest ,
 PXSvMbxRequest_EvWait ,
 PXSvMbxRequest_NoWait ,
 PXSvMbxRelease ,
 PXSvMcRequest ,
 PXSvMcRequest_EvWait ,
 PXSvMcRequest_NoWait ,
 PXSvMcRelease ,
 PXSvOpoolRequest ,


 PXSvOpoolRequest_NoWait ,
 PXSvOpoolRelease ,
 PXSvTrapInstallHandler ,
 PXSvIntInstallHandler ,
 PXSvIntInstallService ,
 PXSvIntInstallFastHandler ,
 PXSvIntInstallFastContextHandler ,
 PXSvSysInfoGetTaskInfo ,
 PXSvSysInfoGetMsgsInMbx ,
 PXSvSysInfoGetMsgInfo ,
 PXSvSysInfoGetMCInfo ,
 PXSvSysInfoGetMbxInfo ,
 PXSvSysInfoGetDelayInfo ,
 PXSvSysInfoGetOpoolInfo ,
 PXSvSysInfoGetNumberOfObjects ,
 PXSvSysInfoGetObjType ,
 PXSvSysInfoGetPeInfo ,
 PXSvSysInfoGetToInfo ,
 PXSvMsgGetProtection ,
 PXSvMsgSetProtection ,
 PXSvSysInfoGetInterruptInfo ,
 PXSvDieService ,
 PXSvServiceTaskInit ,
 PXSvTaskForceTermination ,
 PXSvMsgForceRelease ,
 PXSvSysObjReleaseAllObjects ,
 PXSvMbxRequestMbx ,
 PXSvMbxRegisterMbx ,
 PXSvRegisterRead ,
 PXSvRegisterWrite ,
 PXSvRegisterSetMask ,
 PXSvMbxCheck ,
 PXSvTaskCheck ,
 PXSvMsgSetData ,
 PXSvToRequest_NoWait ,
 PXSvToRequest_EvWait ,
 PXSvPeRequest_NoWait ,
 PXSvPeRequest_EvWait ,
 PXSvTaskGetAccessRights ,
 PXSvRemoveAccessRights ,
 PXSvRestoreAccessRights ,
 PXSvMsgGetSender ,
 PXSvMsgGetMetadata ,
 PXSvMsgSetMetadata ,
 PXSvMcReturnAllBlks ,

 PXSvMessage ,
 PXSvDiesrvInit ,

 PXSvTickDefine_Hnd ,
 PXSvTaskSignalEvents_Hnd ,
 PXSvTaskSuspend_Hnd ,
 PXSvDelaySched_Hnd ,
 PXSvMsgGetData_Hnd ,
 PXSvMsgSend_Hnd ,
 PXSvMsgSend_PrioHnd ,
 PXSvMsgRelease_Hnd ,
 PXSvPeStart_Hnd ,
 PXSvPeStop_Hnd ,
 PXSvToStart_Hnd ,
 PXSvToStop_Hnd ,
 PXSvRegisterRead_Hnd ,
 PXSvRegisterWrite_Hnd ,
 PXSvRegisterSetMask_Hnd ,
 PXSvMsgGetMetadata_Hnd ,
 PXSvMsgSetMetadata_Hnd ,



 
    PXSvTraceEnterScheduling,
    /* define special service numbers for interrupt enter and exit for tracing */
    PXSvIntEntry,
    PXSvIntExit,
    PXSvObjRequest_Waiting,
    T1WaitRelease,
    PXSvLastService,
    PXSvSERVICE_END_MASK = 0x8000
} PxService_t;

#endif /* __pxservices__ */

