/*
 * ENGINEDECODER_ASYNCBUFFER_type.h
 *
 *  Created on: 01.05.2016
 *      Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm, 2016
 */



#ifndef ENGINEDECODER_ASYNCBUFFER_TYPE_H_
#define ENGINEDECODER_ASYNCBUFFER_TYPE_H_

#include "global.h"

/*****************************************************************************************
 *************** Type Definition for ENGINEDECODER_ASYNCBUFFER signal                     **************************
 *****************************************************************************************/

typedef struct
{
	//Current position of the decoder
	sint32_t engineFL_Pos;
	sint32_t engineFR_Pos;
	sint32_t engineRL_Pos;
	sint32_t engineRR_Pos;

	//Bits identifyoing the a decoder has reported the value
	//These bits will be set to 0 upon requesting an update
	union
	{
		uint8_t allEngine;
		struct
		{
			uint8_t fl : 1;
			uint8_t fr : 1;
			uint8_t rl : 1;
			uint8_t rr : 1;
		} engine;
	} status;
} ENGINEDECODER_ASYNCBUFFER_data_t;


#define ENGINEDECODER_ASYNCBUFFER_INIT_DATA ((ENGINEDECODER_ASYNCBUFFER_data_t){0,0,0,0,0})



#endif /* SWC_ENGINE_TYPE_H_ */

