/*
 * ENGINE_type.cpp
 *
 *  Created on: 01.05.2016
 *      Author: Autogenerated
 */



#include "ENGINE_type.h"

extern "C"
{

extern CODD_ENGINE_t CODD_ENGINE_data;

RC_t ENGINE_scaleR2D( const ENGINE_raw_t * const praw, ENGINE_data_t * const pvalue)
{

	return RC_ERROR;
}

RC_t ENGINE_scaleD2R( const ENGINE_data_t * const pvalue, ENGINE_raw_t * const praw)
{
		//Change the conversion after consulting with prof
		CODD_ENGINE_data.wheelspeedFL = pvalue->speed_frontLeft;
		CODD_ENGINE_data.wheelspeedFR = pvalue->speed_frontRight;
		CODD_ENGINE_data.wheelspeedRL = pvalue->speed_rearLeft;
		CODD_ENGINE_data.wheelspeedRR = pvalue->speed_rearRight;

		*praw = &CODD_ENGINE_data;

		return RC_SUCCESS;
}

} //extern  "C"
