/*
 * EVENT_type.h
 *
 *  Created on: 01.05.2016
 *      Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm, 2016
 */



#ifndef EVENT_TYPE_H_
#define EVENT_TYPE_H_

#include "global.h"
#include "pxdef.h"

/*****************************************************************************************
 *************** Type Definition for EVENT signal                     **************************
 *****************************************************************************************/


typedef struct
{
	PxTask_t receiverTask;
	PxEvents_t eventMask;
} EVENT_data_t;


#define EVENT_INIT_DATA ((EVENT_data_t){{0,PXERR_NOERROR},0})



#endif /* SWC_ENGINE_TYPE_H_ */

