/*
 * JOYSTICK_type.h
 *
 *  Created on: 01.05.2016
 *      Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm, 2016
 */



#ifndef JOYSTICK_TYPE_H_
#define JOYSTICK_TYPE_H_

#include "global.h"

/*****************************************************************************************
 *************** Type Definition for JOYSTICK signal            **************************
 *****************************************************************************************/


typedef struct
{
	sint8_t x_in;
	sint8_t y_in;
	sint8_t Rz_in;
	boolean_t emergency_stop;
	boolean_t gradual_stop;
} JOYSTICK_data_t;


#define JOYSTICK_INIT_DATA ((JOYSTICK_data_t){0,0,0, false})  //to be replaced with your own data structure



#endif /* SWC_ENGINE_TYPE_H_ */

