/*
 * LIDARFEATURE_type.h
 *
 *  Created on: 01.05.2016
 *      Author: Autogenerated by H-DA RTE Generator
 */



#ifndef LIDARFEATURE_TYPE_H_
#define LIDARFEATURE_TYPE_H_

#include "global.h"

/*****************************************************************************************
 *************** Type Definition for LIDARFEATURE signal                     **************************
 *****************************************************************************************/



typedef struct
{
	uint8_t data;
} LIDARFEATURE_data_t;


#define LIDARFEATURE_INIT_DATA ((LIDARFEATURE_data_t){0})



#endif /* SWC_ENGINE_TYPE_H_ */

