/*
 * LIDARCONFIG_type.cpp
 *
 *  Created on: 01.05.2016
 *      Author: Autogenerated
 */



#include "LIDARCONFIG_type.h"

extern "C"
{

RC_t LIDARCONFIG_scaleR2D( const LIDARCONFIG_raw_t * const praw, LIDARCONFIG_data_t * const pvalue)
{

	pvalue->speed = (uint8_t)((**praw)>>24);
	pvalue->collissionAngle = (uint8_t)((**praw)>>16);
	pvalue->resolution = (uint16_t)(**praw);

	return RC_SUCCESS;
}

RC_t LIDARCONFIG_scaleD2R( const LIDARCONFIG_data_t * const pvalue, LIDARCONFIG_raw_t * const praw)
{

	(**praw) = ((pvalue->speed) << 24) + ((pvalue->collissionAngle) << 16) + (pvalue->resolution);

	return RC_SUCCESS;
}

} //extern  "C"
