/*
 * REMOTEMSG_type.h
 *
 *  Created on: 01.05.2016
 *      Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm, 2016
 */



#ifndef REMOTEMSG_TYPE_H_
#define REMOTEMSG_TYPE_H_

#include "global.h"

#include "cardataprotocol_type.h"

/*****************************************************************************************
 *************** Type Definition for REMOTEMSG  signal class **************************
 *****************************************************************************************/


/**
 * Raw and data signal are identical to the remote application data structure
 */
#define REMOTEMSG_data_t CARDATAPROTOCOL_data_t

#define REMOTEMSG_INIT_DATA REMOTE_INIT_DATA



#endif /* SWC_ENGINE_TYPE_H_ */

