/*
 * TARGETSPEED_type.cpp
 *
 *  Created on: 01.05.2016
 *      Author: Autogenerated
 */



#include "TARGETSPEED_type.h"

extern "C"
{

RC_t TARGETSPEED_scaleR2D( const TARGETSPEED_raw_t * const praw, TARGETSPEED_data_t * const pvalue)
{


	//Nothing to be done here at the moment....
	return RC_SUCCESS;
}

RC_t TARGETSPEED_scaleD2R( const TARGETSPEED_data_t * const pvalue, TARGETSPEED_raw_t * const praw)
{

	//Nothing to be done here at the moment....
	return RC_SUCCESS;
}


/**
 * Scaler to translate targetspeed into CanOpen Signal for LIDAR
 * @param const ENGINE_data_t * const pvalue ==> INPUT: Pointer to the signal application data object
 * @param TARGETSPEED_raw_t * const praw  ==> Output: Pointer to the signal rawdata object
 */
RC_t TARGETSPEED_scaleD2R_Lidar( const TARGETSPEED_data_t * const pvalue, TARGETSPEED_raw_t * const praw)
{
	(**praw) = 	 (pvalue->vx << 24)  + (pvalue->vy << 16) + (pvalue->vphi << 8);
	return RC_SUCCESS;
}

} //extern  "C"
