/*
 * TOUCH_type.h
 *
 *  Created on: 01.05.2016
 *      Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm, 2016
 */



#ifndef TOUCH_TYPE_H_
#define TOUCH_TYPE_H_

#include "global.h"

#include "conio.h"

/*****************************************************************************************
 *************** Type Definition for TOUCH  signal class **************************
 *****************************************************************************************/

typedef CONIO_PIXEL_t TOUCH_data_t;

#define TOUCH_INIT_DATA ((TOUCH_data_t){0, 0})



#endif /* SWC_ENGINE_TYPE_H_ */

